/*
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.github.packageurl;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public final class PackageURLBuildersTest {
    @Test
    void testAlpm() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:alpm/arch/pacman@6.0.1-1?arch=x86_64")
                        .build(),
                PackageURLBuilders.alpm()
                        .withVendor("arch")
                        .withName("pacman")
                        .withVersion("6.0.1-1")
                        .withArch("x86_64")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:alpm/arch/python-pip@21.0-1?arch=any")
                        .build(),
                PackageURLBuilders.alpm()
                        .withVendor("arch")
                        .withName("python-pip")
                        .withVersion("21.0-1")
                        .withArch("any")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:alpm/arch/containers-common@1:0.47.4-4?arch=x86_64")
                        .build(),
                PackageURLBuilders.alpm()
                        .withVendor("arch")
                        .withName("containers-common")
                        .withVersion("1:0.47.4-4")
                        .withArch("x86_64")
                        .build());
    }

    @Test
    void testApk() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:apk/alpine/curl@7.83.0-r0?arch=x86")
                        .build(),
                PackageURLBuilders.apk()
                        .withVendor("alpine")
                        .withName("curl")
                        .withVersion("7.83.0-r0")
                        .withArch("x86")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:apk/alpine/apk@2.12.9-r3?arch=x86")
                        .build(),
                PackageURLBuilders.apk()
                        .withVendor("alpine")
                        .withName("apk")
                        .withVersion("2.12.9-r3")
                        .withArch("x86")
                        .build());
    }

    @Test
    void testBazel() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bazel/rules_java@7.8.0").build(),
                PackageURLBuilders.bazel()
                        .withName("rules_java")
                        .withVersion("7.8.0")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bazel/curl@8.8.0.bcr.1").build(),
                PackageURLBuilders.bazel()
                        .withName("curl")
                        .withVersion("8.8.0.bcr.1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bazel/curl@8.8.0?repository_url=https://example.org/bazel-registry")
                        .build(),
                PackageURLBuilders.bazel()
                        .withName("curl")
                        .withVersion("8.8.0")
                        .withRepositoryUrl("https://example.org/bazel-registry")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bazel/rules_java@8.5.0#java/runfiles")
                        .build(),
                PackageURLBuilders.bazel()
                        .withName("rules_java")
                        .withVersion("8.5.0")
                        .withLabel("java/runfiles")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bazel/rules_java@8.5.0#java/runfiles:runfiles")
                        .build(),
                PackageURLBuilders.bazel()
                        .withName("rules_java")
                        .withVersion("8.5.0")
                        .withLabel("java/runfiles:runfiles")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bazel/rules_go@0.48.0#go").build(),
                PackageURLBuilders.bazel()
                        .withName("rules_go")
                        .withVersion("0.48.0")
                        .withLabel("go")
                        .build());
    }

    @Test
    void testBitbucket() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bitbucket/birkenfeld/pygments-main@244fd47e07d1014f0aed9c")
                        .build(),
                PackageURLBuilders.bitbucket()
                        .withOrganization("birkenfeld")
                        .withRepositoryName("pygments-main")
                        .withCommit("244fd47e07d1014f0aed9c")
                        .build());
    }

    @Test
    void testBitnami() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bitnami/wordpress?distro=debian-12")
                        .build(),
                PackageURLBuilders.bitnami()
                        .withName("wordpress")
                        .withDistro("debian-12")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bitnami/wordpress@6.2.0?distro=debian-12")
                        .build(),
                PackageURLBuilders.bitnami()
                        .withName("wordpress")
                        .withVersion("6.2.0")
                        .withDistro("debian-12")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bitnami/wordpress@6.2.0?arch=arm64&distro=debian-12")
                        .build(),
                PackageURLBuilders.bitnami()
                        .withName("wordpress")
                        .withVersion("6.2.0")
                        .withArch("arm64")
                        .withDistro("debian-12")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:bitnami/wordpress@6.2.0?arch=arm64&distro=photon-4")
                        .build(),
                PackageURLBuilders.bitnami()
                        .withName("wordpress")
                        .withVersion("6.2.0")
                        .withArch("arm64")
                        .withDistro("photon-4")
                        .build());
    }

    @Test
    void testCargo() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cargo/rand@0.7.2").build(),
                PackageURLBuilders.cargo().withName("rand").withVersion("0.7.2").build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cargo/clap@2.33.0").build(),
                PackageURLBuilders.cargo()
                        .withName("clap")
                        .withVersion("2.33.0")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cargo/structopt@0.3.11").build(),
                PackageURLBuilders.cargo()
                        .withName("structopt")
                        .withVersion("0.3.11")
                        .build());
    }

    @Test
    void testCocoapods() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cocoapods/AFNetworking@4.0.1")
                        .build(),
                PackageURLBuilders.cocoapods()
                        .withPodName("AFNetworking")
                        .withPackageVersion("4.0.1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cocoapods/MapsIndoors@3.24.0")
                        .build(),
                PackageURLBuilders.cocoapods()
                        .withPodName("MapsIndoors")
                        .withPackageVersion("3.24.0")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cocoapods/ShareKit@2.0#Twitter")
                        .build(),
                PackageURLBuilders.cocoapods()
                        .withPodName("ShareKit")
                        .withPackageVersion("2.0")
                        .withSubpath("Twitter")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cocoapods/GoogleUtilities@7.5.2#NSData+zlib")
                        .build(),
                PackageURLBuilders.cocoapods()
                        .withPodName("GoogleUtilities")
                        .withPackageVersion("7.5.2")
                        .withSubpath("NSData+zlib")
                        .build());
    }

    @Test
    void testComposer() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:composer/laravel/laravel@5.5.0")
                        .build(),
                PackageURLBuilders.composer()
                        .withVendor("laravel")
                        .withName("laravel")
                        .withVersion("5.5.0")
                        .build());
    }

    @Test
    void testConan() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:conan/openssl@3.0.3").build(),
                PackageURLBuilders.conan()
                        .withPackageName("openssl")
                        .withPackageVersion("3.0.3")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:conan/openssl.org/openssl@3.0.3?user=bincrafters&channel=stable")
                        .build(),
                PackageURLBuilders.conan()
                        .withVendor("openssl.org")
                        .withPackageName("openssl")
                        .withPackageVersion("3.0.3")
                        .withUser("bincrafters")
                        .withChannel("stable")
                        .build());
        // FIXME: Definition missing these qualifiers
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:conan/openssl.org/openssl@3.0.3?arch=x86_64&build_type=Debug&compiler=Visual%20Studio&compiler.runtime=MDd&compiler.version=16&os=Windows&shared=True&rrev=93a82349c31917d2d674d22065c7a9ef9f380c8e&prev=b429db8a0e324114c25ec387bfd8281f330d7c5c")
                        .build(),
                PackageURLBuilders.conan()
                        .withVendor("openssl.org")
                        .withPackageName("openssl")
                        .withPackageVersion("3.0.3")
                        .withArch("x86_64")
                        .withBuildType("Debug")
                        .withCompiler("Visual Studio")
                        .withCompilerRuntime("MDd")
                        .withCompilerVersion("16")
                        .withOs("Windows")
                        .withShared("True")
                        .withRecipeRevision("93a82349c31917d2d674d22065c7a9ef9f380c8e")
                        .withPackageRevision("b429db8a0e324114c25ec387bfd8281f330d7c5c")
                        .build());
    }

    @Test
    void testConda() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:conda/absl-py@0.4.1?build=py36h06a4308_0&channel=main&subdir=linux-64&type=tar.bz2")
                        .build(),
                PackageURLBuilders.conda()
                        .withName("absl-py")
                        .withVersion("0.4.1")
                        .withBuild("py36h06a4308_0")
                        .withChannel("main")
                        .withSubdir("linux-64")
                        .withPackageType("tar.bz2")
                        .build());
    }

    @Test
    void testCpan() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cpan/GDT/URI-PackageURL").build(),
                PackageURLBuilders.cpan()
                        .withCpanId("GDT")
                        .withDistributionName("URI-PackageURL")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cpan/OALDERS/libwww-perl@6.76")
                        .build(),
                PackageURLBuilders.cpan()
                        .withCpanId("OALDERS")
                        .withDistributionName("libwww-perl")
                        .withVersion("6.76")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cpan/DROLSKY/DateTime@1.55?repository_url=backpan.perl.org")
                        .build(),
                PackageURLBuilders.cpan()
                        .withCpanId("DROLSKY")
                        .withDistributionName("DateTime")
                        .withVersion("1.55")
                        .withRepositoryUrl("backpan.perl.org")
                        .build());
    }

    @Test
    void testCran() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cran/A3@1.0.0").build(),
                PackageURLBuilders.cran().withName("A3").withVersion("1.0.0").build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cran/rJava@1.0-4").build(),
                PackageURLBuilders.cran().withName("rJava").withVersion("1.0-4").build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:cran/caret@6.0-88").build(),
                PackageURLBuilders.cran()
                        .withName("caret")
                        .withVersion("6.0-88")
                        .build());
    }

    @Test
    void testDeb() throws MalformedPackageURLException {
        // FIXME: Definition missing distro qualifier
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:deb/debian/curl@7.50.3-1?arch=i386&distro=jessie")
                        .build(),
                PackageURLBuilders.deb()
                        .withVendor("debian")
                        .withName("curl")
                        .withVersion("7.50.3-1")
                        .withArch("i386")
                        .withDistro("jessie")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:deb/debian/dpkg@1.19.0.4?arch=amd64&distro=stretch")
                        .build(),
                PackageURLBuilders.deb()
                        .withVendor("debian")
                        .withName("dpkg")
                        .withVersion("1.19.0.4")
                        .withArch("amd64")
                        .withDistro("stretch")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:deb/ubuntu/dpkg@1.19.0.4?arch=amd64")
                        .build(),
                PackageURLBuilders.deb()
                        .withVendor("ubuntu")
                        .withName("dpkg")
                        .withVersion("1.19.0.4")
                        .withArch("amd64")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:deb/debian/attr@1:2.4.47-2?arch=source")
                        .build(),
                PackageURLBuilders.deb()
                        .withVendor("debian")
                        .withName("attr")
                        .withVersion("1:2.4.47-2")
                        .withArch("source")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:deb/debian/attr@1:2.4.47-2%2Bb1?arch=amd64")
                        .build(),
                PackageURLBuilders.deb()
                        .withVendor("debian")
                        .withName("attr")
                        .withVersion("1:2.4.47-2+b1")
                        .withArch("amd64")
                        .build());
    }

    @Test
    void testDocker() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:docker/cassandra@latest").build(),
                PackageURLBuilders.docker()
                        .withName("cassandra")
                        .withVersion("latest")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:docker/smartentry/debian@dc437cc87d10")
                        .build(),
                PackageURLBuilders.docker()
                        .withName("debian")
                        .withVersion("dc437cc87d10")
                        .withRegistry("smartentry")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:docker/customer/dockerimage@sha256%3A244fd47e07d10?repository_url=gcr.io")
                        .build(),
                PackageURLBuilders.docker()
                        .withName("dockerimage")
                        .withVersion("sha256:244fd47e07d10")
                        .withRegistry("customer")
                        .withRepositoryUrl("gcr.io")
                        .build());
    }

    @Test
    void testGem() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:gem/ruby-advisory-db-check@0.12.4")
                        .build(),
                PackageURLBuilders.gem()
                        .withName("ruby-advisory-db-check")
                        .withVersion("0.12.4")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:gem/jruby-launcher@1.1.2?platform=java")
                        .build(),
                PackageURLBuilders.gem()
                        .withName("jruby-launcher")
                        .withVersion("1.1.2")
                        .withPlatform("java")
                        .build());
    }

    @Test
    void testGeneric() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:generic/openssl@1.1.10g").build(),
                PackageURLBuilders.generic()
                        .withName("openssl")
                        .withVersion("1.1.10g")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:generic/openssl@1.1.10g?download_url=https://openssl.org/source/openssl-1.1.0g.tar.gz&checksum=sha256:de4d501267da")
                        .build(),
                PackageURLBuilders.generic()
                        .withName("openssl")
                        .withVersion("1.1.10g")
                        .withDownloadUrl("https://openssl.org/source/openssl-1.1.0g.tar.gz")
                        .withChecksum("sha256:de4d501267da")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:generic/bitwarderl?vcs_url=git%2Bhttps://git.fsfe.org/dxtr/bitwarderl%40cc55108da32")
                        .build(),
                PackageURLBuilders.generic()
                        .withName("bitwarderl")
                        .withVcsUrl("git+https://git.fsfe.org/dxtr/bitwarderl@cc55108da32")
                        .build());
    }

    @Test
    void testGithub() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:github/package-url/purl-spec@244fd47e07d1004")
                        .build(),
                PackageURLBuilders.github()
                        .withOrganization("package-url")
                        .withRepositoryName("purl-spec")
                        .withCommit("244fd47e07d1004")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:github/package-url/purl-spec@244fd47e07d1004#everybody/loves/dogs")
                        .build(),
                PackageURLBuilders.github()
                        .withOrganization("package-url")
                        .withRepositoryName("purl-spec")
                        .withCommit("244fd47e07d1004")
                        .withSubpath("everybody/loves/dogs")
                        .build());
    }

    @Test
    void testGolang() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:golang/github.com/gorilla%2Fcontext@234fd47e07d1004f0aed9c")
                        .build(),
                PackageURLBuilders.golang()
                        .withNamespace("github.com")
                        .withName("gorilla/context")
                        .withVersion("234fd47e07d1004f0aed9c")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:golang/google.golang.org/genproto#googleapis/api/annotations")
                        .build(),
                PackageURLBuilders.golang()
                        .withNamespace("google.golang.org")
                        .withName("genproto")
                        .withSubpath("googleapis/api/annotations")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:golang/github.com/gorilla%2Fcontext@234fd47e07d1004f0aed9c#api")
                        .build(),
                PackageURLBuilders.golang()
                        .withNamespace("github.com")
                        .withName("gorilla/context")
                        .withVersion("234fd47e07d1004f0aed9c")
                        .withSubpath("api")
                        .build());
    }

    @Test
    void testHackage() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:hackage/a50@0.5").build(),
                PackageURLBuilders.hackage().withName("a50").withVersion("0.5").build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:hackage/AC-HalfInteger@1.2.1")
                        .build(),
                PackageURLBuilders.hackage()
                        .withName("AC-HalfInteger")
                        .withVersion("1.2.1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:hackage/3d-graphics-examples@0.0.0.2")
                        .build(),
                PackageURLBuilders.hackage()
                        .withName("3d-graphics-examples")
                        .withVersion("0.0.0.2")
                        .build());
    }

    @Test
    void testHex() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:hex/jason@1.1.2").build(),
                PackageURLBuilders.hex().withName("jason").withVersion("1.1.2").build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:hex/acme/foo@2.3.").build(),
                PackageURLBuilders.hex()
                        .withOrganization("acme")
                        .withName("foo")
                        .withVersion("2.3.")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:hex/phoenix_html@2.13.3#priv/static/phoenix_html.js")
                        .build(),
                PackageURLBuilders.hex()
                        .withName("phoenix_html")
                        .withVersion("2.13.3")
                        .withSubpath("priv/static/phoenix_html.js")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:hex/bar@1.2.3?repository_url=https://myrepo.example.com")
                        .build(),
                PackageURLBuilders.hex()
                        .withName("bar")
                        .withVersion("1.2.3")
                        .withRepositoryUrl("https://myrepo.example.com")
                        .build());
    }

    @Test
    void testHuggingface() throws MalformedPackageURLException {
        // FIXME: Example missing required organization
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:huggingface/distilbert/distilbert-base-uncased@043235d6088ecd3dd5fb5ca3592b6913fd516027")
                        .build(),
                PackageURLBuilders.huggingface()
                        .withOrganization("distilbert")
                        .withName("distilbert-base-uncased")
                        .withCommit("043235d6088ecd3dd5fb5ca3592b6913fd516027")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:huggingface/microsoft/deberta-v3-base@559062ad13d311b87b2c455e67dcd5f1c8f65111?repository_url=https://hub-ci.huggingface.co")
                        .build(),
                PackageURLBuilders.huggingface()
                        .withOrganization("microsoft")
                        .withName("deberta-v3-base")
                        .withCommit("559062ad13d311b87b2c455e67dcd5f1c8f65111")
                        .withRepositoryUrl("https://hub-ci.huggingface.co")
                        .build());
    }

    @Test
    void testJulia() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:julia/Dates@1.9.0?uuid=ade2ca70-3891-5945-98fb-dc099432e06a")
                        .build(),
                PackageURLBuilders.julia()
                        .withName("Dates")
                        .withVersion("1.9.0")
                        .withUuid("ade2ca70-3891-5945-98fb-dc099432e06a")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:julia/Dates?uuid=ade2ca70-3891-5945-98fb-dc099432e06a")
                        .build(),
                PackageURLBuilders.julia()
                        .withName("Dates")
                        .withUuid("ade2ca70-3891-5945-98fb-dc099432e06a")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:julia/RegisterQD@0.3.1?uuid=ac24ea0c-1830-11e9-18d4-81f172323054")
                        .build(),
                PackageURLBuilders.julia()
                        .withName("RegisterQD")
                        .withVersion("0.3.1")
                        .withUuid("ac24ea0c-1830-11e9-18d4-81f172323054")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:julia/RegisterQD@0.3.1?uuid=ac24ea0c-1830-11e9-18d4-81f172323054&repository_url=https://github.com/HolyLab/HolyLabRegistry")
                        .build(),
                PackageURLBuilders.julia()
                        .withName("RegisterQD")
                        .withVersion("0.3.1")
                        .withUuid("ac24ea0c-1830-11e9-18d4-81f172323054")
                        .withRepositoryUrl("https://github.com/HolyLab/HolyLabRegistry")
                        .build());
    }

    @Test
    void testLuarocks() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:luarocks/luasocket@3.1.0-1").build(),
                PackageURLBuilders.luarocks()
                        .withName("luasocket")
                        .withVersionRevision("3.1.0-1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:luarocks/hisham/luafilesystem@1.8.0-1")
                        .build(),
                PackageURLBuilders.luarocks()
                        .withManifest("hisham")
                        .withName("luafilesystem")
                        .withVersionRevision("1.8.0-1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:luarocks/username/packagename@0.1.0-1?repository_url=https://example.com/private_rocks_server/")
                        .build(),
                PackageURLBuilders.luarocks()
                        .withManifest("username")
                        .withName("packagename")
                        .withVersionRevision("0.1.0-1")
                        .withRepositoryUrl("https://example.com/private_rocks_server/")
                        .build());
    }

    @Test
    void testMaven() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1")
                        .build(),
                PackageURLBuilders.maven()
                        .withGroupId("org.apache.xmlgraphics")
                        .withArtifactId("batik-anim")
                        .withVersion("1.9.1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?type=pom")
                        .build(),
                PackageURLBuilders.maven()
                        .withGroupId("org.apache.xmlgraphics")
                        .withArtifactId("batik-anim")
                        .withVersion("1.9.1")
                        .withType("pom")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?classifier=sources")
                        .build(),
                PackageURLBuilders.maven()
                        .withGroupId("org.apache.xmlgraphics")
                        .withArtifactId("batik-anim")
                        .withVersion("1.9.1")
                        .withClassifier("sources")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?type=zip&classifier=dist")
                        .build(),
                PackageURLBuilders.maven()
                        .withGroupId("org.apache.xmlgraphics")
                        .withArtifactId("batik-anim")
                        .withVersion("1.9.1")
                        .withType("zip")
                        .withClassifier("dist")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:maven/net.sf.jacob-projec/jacob@1.14.3?classifier=x86&type=dll")
                        .build(),
                PackageURLBuilders.maven()
                        .withGroupId("net.sf.jacob-projec")
                        .withArtifactId("jacob")
                        .withVersion("1.14.3")
                        .withClassifier("x86")
                        .withType("dll")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:maven/net.sf.jacob-projec/jacob@1.14.3?classifier=x64&type=dll")
                        .build(),
                PackageURLBuilders.maven()
                        .withGroupId("net.sf.jacob-projec")
                        .withArtifactId("jacob")
                        .withVersion("1.14.3")
                        .withClassifier("x64")
                        .withType("dll")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:maven/groovy/groovy@1.0?repository_url=https://maven.google.com")
                        .build(),
                PackageURLBuilders.maven()
                        .withGroupId("groovy")
                        .withArtifactId("groovy")
                        .withVersion("1.0")
                        .withRepositoryUrl("https://maven.google.com")
                        .build());
    }

    @Test
    void testMlflow() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:mlflow/creditfraud@3?repository_url=https://westus2.api.azureml.ms/mlflow/v1.0/subscriptions/a50f2011-fab8-4164-af23-c62881ef8c95/resourceGroups/TestResourceGroup/providers/Microsoft.MachineLearningServices/workspaces/TestWorkspace")
                        .build(),
                PackageURLBuilders.mlflow()
                        .withName("creditfraud")
                        .withVersion("3")
                        .withRepositoryUrl(
                                "https://westus2.api.azureml.ms/mlflow/v1.0/subscriptions/a50f2011-fab8-4164-af23-c62881ef8c95/resourceGroups/TestResourceGroup/providers/Microsoft.MachineLearningServices/workspaces/TestWorkspace")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:mlflow/trafficsigns@10?model_uuid=36233173b22f4c89b451f1228d700d49&run_id=410a3121-2709-4f88-98dd-dba0ef056b0a&repository_url=https://adb-5245952564735461.0.azuredatabricks.net/api/2.0/mlflow")
                        .build(),
                PackageURLBuilders.mlflow()
                        .withName("trafficsigns")
                        .withVersion("10")
                        .withModelUuid("36233173b22f4c89b451f1228d700d49")
                        .withRunId("410a3121-2709-4f88-98dd-dba0ef056b0a")
                        .withRepositoryUrl("https://adb-5245952564735461.0.azuredatabricks.net/api/2.0/mlflow")
                        .build());
    }

    @Test
    void testNpm() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:npm/foobar@12.3.1").build(),
                PackageURLBuilders.npm()
                        .withName("foobar")
                        .withVersion("12.3.1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:npm/%40angular/animation@12.3.1")
                        .build(),
                PackageURLBuilders.npm()
                        .withScope("@angular")
                        .withName("animation")
                        .withVersion("12.3.1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:npm/mypackage@12.4.5?vcs_url=git://host.com/path/to/repo.git%404345abcd34343")
                        .build(),
                PackageURLBuilders.npm()
                        .withName("mypackage")
                        .withVersion("12.4.5")
                        .withVcsUrl("git://host.com/path/to/repo.git@4345abcd34343")
                        .build());
    }

    @Test
    void testNuget() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:nuget/EnterpriseLibrary.Common@6.0.1304")
                        .build(),
                PackageURLBuilders.nuget()
                        .withName("EnterpriseLibrary.Common")
                        .withVersion("6.0.1304")
                        .build());
    }

    @Test
    void testOci() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:oci/debian@sha256%3A244fd47e07d10?repository_url=docker.io/library/debian&arch=amd64&tag=latest")
                        .build(),
                PackageURLBuilders.oci()
                        .withName("debian")
                        .withVersion("sha256:244fd47e07d10")
                        .withRepositoryUrl("docker.io/library/debian")
                        .withArch("amd64")
                        .withTag("latest")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:oci/debian@sha256%3A244fd47e07d10?repository_url=ghcr.io/debian&tag=bullseye")
                        .build(),
                PackageURLBuilders.oci()
                        .withName("debian")
                        .withVersion("sha256:244fd47e07d10")
                        .withRepositoryUrl("ghcr.io/debian")
                        .withTag("bullseye")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:oci/static@sha256%3A244fd47e07d10?repository_url=gcr.io/distroless/static&tag=latest")
                        .build(),
                PackageURLBuilders.oci()
                        .withName("static")
                        .withVersion("sha256:244fd47e07d10")
                        .withRepositoryUrl("gcr.io/distroless/static")
                        .withTag("latest")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:oci/hello-wasm@sha256:244fd47e07d10?tag=v1")
                        .build(),
                PackageURLBuilders.oci()
                        .withName("hello-wasm")
                        .withVersion("sha256:244fd47e07d10")
                        .withTag("v1")
                        .build());
    }

    @Test
    void testPub() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:pub/characters@1.2.0").build(),
                PackageURLBuilders.pub()
                        .withName("characters")
                        .withVersion("1.2.0")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:pub/flutter@0.0.0").build(),
                PackageURLBuilders.pub()
                        .withName("flutter")
                        .withVersion("0.0.0")
                        .build());
    }

    @Test
    void testPypi() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:pypi/django@1.11.1").build(),
                PackageURLBuilders.pypi()
                        .withName("django")
                        .withVersion("1.11.1")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:pypi/django@1.11.1?file_name=Django-1.11.1.tar.gz")
                        .build(),
                PackageURLBuilders.pypi()
                        .withName("django")
                        .withVersion("1.11.1")
                        .withFileName("Django-1.11.1.tar.gz")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:pypi/django@1.11.1?file_name=Django-1.11.1-py2.py3-none-any.whl")
                        .build(),
                PackageURLBuilders.pypi()
                        .withName("django")
                        .withVersion("1.11.1")
                        .withFileName("Django-1.11.1-py2.py3-none-any.whl")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:pypi/django-allauth@12.23").build(),
                PackageURLBuilders.pypi()
                        .withName("django-allauth")
                        .withVersion("12.23")
                        .build());
    }

    @Test
    void testQpkg() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:qpkg/blackberry/com.qnx.sdp@7.0.0.SGA201702151847")
                        .build(),
                PackageURLBuilders.qpkg()
                        .withVendor("blackberry")
                        .withName("com.qnx.sdp")
                        .withVersion("7.0.0.SGA201702151847")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:qpkg/blackberry/com.qnx.qnx710.foo.bar.qux@0.0.4.01449T202205040833L")
                        .build(),
                PackageURLBuilders.qpkg()
                        .withVendor("blackberry")
                        .withName("com.qnx.qnx710.foo.bar.qux")
                        .withVersion("0.0.4.01449T202205040833L")
                        .build());
    }

    @Test
    void testRpm() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:rpm/fedora/curl@7.50.3-1.fc25?arch=i386&distro=fedora-25")
                        .build(),
                PackageURLBuilders.rpm()
                        .withVendor("fedora")
                        .withName("curl")
                        .withVersionRelease("7.50.3-1.fc25")
                        .withArch("i386")
                        .withDistro("fedora-25")
                        .build());
        // FIXME: Example missing required vendor
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:rpm/fedora/centerim@4.22.10-1.el6?arch=i686&epoch=1&distro=fedora-25")
                        .build(),
                PackageURLBuilders.rpm()
                        .withVendor("fedora")
                        .withName("centerim")
                        .withVersionRelease("4.22.10-1.el6")
                        .withArch("i686")
                        .withEpoch("1")
                        .withDistro("fedora-25")
                        .build());
    }

    @Test
    void testSwid() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:swid/Acme/example.com%2FEnterprise+Server@1.0.0?tag_id=75b8c285-fa7b-485b-b199-4745e3004d0d")
                        .build(),
                PackageURLBuilders.swid()
                        .withSoftwareCreator("Acme")
                        .withSoftwareIdentityName("example.com/Enterprise+Server")
                        .withSoftwareIdentityVersion("1.0.0")
                        .withTagId("75b8c285-fa7b-485b-b199-4745e3004d0d")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:swid/Fedora@29?tag_id=org.fedoraproject.Fedora-29")
                        .build(),
                PackageURLBuilders.swid()
                        .withSoftwareIdentityName("Fedora")
                        .withSoftwareIdentityVersion("29")
                        .withTagId("org.fedoraproject.Fedora-29")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL(
                                "pkg:swid/Adobe%2BSystems%2BIncorporated/Adobe%2BInDesign@CC?tag_id=CreativeCloud-CS6-Win-GM-MUL")
                        .build(),
                PackageURLBuilders.swid()
                        .withSoftwareCreator("Adobe+Systems+Incorporated")
                        .withSoftwareIdentityName("Adobe+InDesign")
                        .withSoftwareIdentityVersion("CC")
                        .withTagId("CreativeCloud-CS6-Win-GM-MUL")
                        .build());
    }

    @Test
    void testSwift() throws MalformedPackageURLException {
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:swift/github.com/Alamofire/Alamofire@5.4.3")
                        .build(),
                PackageURLBuilders.swift()
                        .withNamespace("github.com/Alamofire")
                        .withRepositoryName("Alamofire")
                        .withPackageVersion("5.4.3")
                        .build());
        assertEquals(
                PackageURLBuilder.aPackageURL("pkg:swift/github.com/RxSwiftCommunity/RxFlow@2.12.4")
                        .build(),
                PackageURLBuilders.swift()
                        .withNamespace("github.com/RxSwiftCommunity")
                        .withRepositoryName("RxFlow")
                        .withPackageVersion("2.12.4")
                        .build());
    }
}
