name: CI

on: [push, pull_request]

permissions: {}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]
        distro: [ 'zulu', 'temurin' ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:

    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
      with:
        persist-credentials: false
        submodules: 'true'

    - name: Set up JDK 8 and ${{ matrix.java-version }}
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # tag=v5.7.0
      with:
        distribution: ${{ matrix.distro }}
        # We install two JDKs:
        # * The first one is used by tests through Maven Toolchains.
        # * The second one is used by Maven itself to perform the build.
        #
        # WARNING: The order matters.
        #          The last version specified will be assigned to JAVA_HOME.
        java-version: |
          8
          ${{ matrix.java-version }}

    - name: Build with Maven
      shell: bash
      run: mvn verify

  lint-gha:
    name: Lint GitHub Actions
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
